<?php

// $id


function datepicker_form_alter(&$form, $form_state, $form_id) {
  if (isset($form['type']['#value']) && $form_id == $form['type']['#value'] .'_node_form') {
    // node edit form
    if (variable_get('event_nodeapi_'. $form['type']['#value'], 'never') != 'never') {
      $path = drupal_get_path('module', 'datepicker');
      drupal_add_css($path .'/datePicker.css');
      drupal_add_js($path .'/date.js');
      drupal_add_js($path .'/jquery.datePicker.js');
      $form['event']['start_exploded']['#suffix'] = '<a id="event-datepicker-start" href="#">'. t('Select start date') .'</a>';
      datepicker_add_picker('start');
      $form['event']['end_exploded']['#suffix'] = '<a id="event-datepicker-end" href="#">'. t('Select end date') .'</a>';
      datepicker_add_picker('end');
    }
  }
}

function datepicker_add_picker($value) {
$js = <<<JAVASCRIPT_CODE
  $(function() {
$('#event-datepicker-$value')
    .datePicker(
      // associate the link with a date picker
      {
        createButton:false,
        startDate:'01/01/2007',
        endDate:'31/12/2012'
      }
    ).bind(
      // when the link is clicked display the date picker
      'click',
      function()
      {
        updateSelects($(this).dpGetSelected()[0]);
        $(this).dpDisplay();
        return false;
      }
    ).bind(
      // when a date is selected update the SELECTs
      'dateSelected',
      function(e, selectedDate, \$td, state)
      {
        updateSelects(selectedDate);
      }
    ).bind(
      'dpClosed',
      function(e, selected)
      {
        updateSelects(selected[0]);
      }
    );
    
  var updateSelects = function (selectedDate)
  {
    var selectedDate = new Date(selectedDate);
    $('#edit-event-$value-exploded-day').val(selectedDate.getDate());
    $('#edit-event-$value-exploded-month option[value=' + selectedDate.asString('mm') + ']').attr('selected', 'selected');
    $('#edit-event-$value-exploded-year').val(selectedDate.getFullYear());
  }
  // listen for when the selects are changed and update the picker
  $('#edit-event-$value-exploded-day, #edit-event-$value-exploded-month, #edit-event-$value-exploded-year')
    .bind(
      'change',
      function()
      {
        var d = new Date(
              $('#edit-event-$value-exploded-year').val(),
              $('#edit-event-$value-exploded-month').val()-1,
              $('#edit-event-$value-exploded-day').val()
            );
        $('#event-datepicker-$value').dpSetSelected(d.asString());
      }
    );
  
  // and update the datePicker to reflect it...
  $('#edit-event-$value-exploded-day').trigger('change');
});
JAVASCRIPT_CODE;
  drupal_add_js($js,'inline','footer');
}

